name: "Integrate Blog"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull blog
        run: |
          git clone --depth=1 https://github.com/tanq16/blog_site
          mv ./blog_site/blog ./blog
          rm -rf blog_site

      - name: Deploy blog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "tanishq-github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "auto-add blog"
          git push

